### ISSUE TITLE
Inconsistent profile rendering

### ISSUE THREAD

**Issue by amicks** [CruzHacks/cruzhacks-react#8]
I just noticed this when checking cruzhacks.com on my desktop.  Seems like multi-line titles or names messes up the alignment.

On my rMBP (1440x900) with Chrome v69:
<img width="696" alt="screen shot 2018-10-23 at 13 55 29" src="https://user-images.githubusercontent.com/14898869/47390102-666e2600-d6cb-11e8-912f-2977f23b950b.png">

On my rMBP (1440x900) with Safari v12:
<img width="734" alt="screen shot 2018-10-23 at 13 50 25" src="https://user-images.githubusercontent.com/14898869/47390110-6c640700-d6cb-11e8-98e8-59223494c81b.png">

On Windows 10 desktop (1920x1080) with Chrome v70:
![screenshot_10](https://user-images.githubusercontent.com/14898869/47390013-28710200-d6cb-11e8-8b52-5670247a6ec3.png)

**Comment by greg-wolff** [comment]
this is a result of the way the borders are setup. since gradient borders
aren't native css, i think karthik did a background with foreground profile
image in it

the solution here should be to scale the height of the card and retain the
profile size. ideally the card could still be aligned along the top, and
different sizes on the bottom would be okay

**Comment by kartmanny** [comment]
Patched!
